### ISSUE TITLE
Provide a way to add additionnal packages to specify own httpd_packages ?

### ISSUE THREAD

**Issue by flotho** [robertdebock/ansible-role-httpd#17]
Hi @robertdebock 
Once again, big thanks for all your collection, suc amazing roles here !

I would like to add more module in my httpd configuration and AFAICS https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence the httpd_packages of your role will mostly have the latest word in the 15 position.
I would propose to make httpd_packages join 2 variables, the minimal one and a new custom one available to setup for everyone.
What's your point of view?

**Comment by robertdebock** [comment]
Sounds like a good plan! I'm off for the next two weeks, but certainly, please make a PR.

I'd like to keep the "difficult stuff" in vars/main.yml, to try and keep tasks/main.yml readable.

Looking forward to your PR!

Regards, Robert.

**Comment by flotho** [comment]
enjoy your holidays
