### ISSUE TITLE
Add options to not create ssl.conf and default_vhost.conf

### ISSUE THREAD

**Issue by gesinn-it-gea** [robertdebock/ansible-role-httpd#9]
## Proposed feature

Add options to not create ssl.conf and default_vhost.conf

## Rationale

ssl.conf and default_vhost.conf are always created. Depending on other confs added, this could lead to Apache error "module ssl_module is already loaded, skipping" and "Cannot define multiple Listeners on the same IP:port" during Ansilble provisioning

## Additional context

Would it make sense to add conditionals to the specific tasks and evaluate variables like "httpd_config_skip_ssl.conf" and "httpd_config_skip_default_vhost.conf"?

**Comment by robertdebock** [comment]
I think you are correct. Looking back at this role; I think SSL should be taken out by default, but can be optionally enabled. Let me review the role.

Thanks for bringing this issue up.

**Comment by robertdebock** [comment]
First commits are done and tests are running... I'm on a camping, wifi is pretty terrible, so this will take some more time.

**Comment by gesinn-it-gea** [comment]
Hey Robert, enjoy your summer holidays! I really like your Ansible roles.

**Comment by robertdebock** [comment]
Okay, it's in the last release. I'm hoping the rest of the roles that use this role do not break, let's see.

Thanks again for convincing me to pull the trigger on this one.
